apps/gui/app/views.py
import os

from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    flash,
    current_app,
    send_from_directory,
)
from flask_login import login_required, login_user, logout_user, current_user
from xkcdpass import xkcd_password as xp
from sqlalchemy import select
from werkzeug import Response
from werkzeug.utils import secure_filename
import pyotp

from app import ResticWorker, DeviceInfo, SyncthingWorker
from app.models import db, Task
from app.forms import (LoginForm, RegistrationForm, UploadForm, AddSyncDeviceForm,
                       RebootDeviceForm, ShutdownDeviceForm, AddSyncDeviceToFolderForm, TOTPForm, SyncFolderBackupForm)
from app.models import User

main = Blueprint("main", __name__, template_folder="templates")
auth = Blueprint("auth", __name__, template_folder="templates")


@login_required  # type: ignore[misc]
@main.route("/backup", methods=["GET", "POST"])
def backup():
    """uploading files to backup"""
    if not current_user.is_authenticated:
        return redirect(url_for("main.index"))

    upload_form = UploadForm()
    if upload_form.validate_on_submit():
        list_of_files = []
        for f in upload_form.backup_files.data:
            filename = secure_filename(f.filename)
            file_with_path = os.path.join(
                current_app.config["RESTIC_UPLOAD_DIR"], filename
            )
            f.save(file_with_path)
            list_of_files.append(file_with_path)

        if current_user.get_task_in_progress("backup_files"):
            flash("An backup_files task is currently in progress")
            return render_template("index.html", title="Home")

        try:
            task = current_user.launch_task("backup_files", list_of_files)
            db.session.commit()
        except Exception as exc:
            raise RuntimeError from exc
        flash(f"Backup started, task-id: {task.id}")

    sync_backup_form = SyncFolderBackupForm()
    if sync_backup_form.validate_on_submit():
        if current_user.get_task_in_progress("backup_files"):
            flash("An backup_files task is currently in progress")
            return render_template("index.html", title="Home")

        default_folder = current_app.config["SYNCTHING_DEFAULT_FOLDER_PATH"]
        list_of_files = [os.path.join(dirpath, f) for (dirpath, dirnames, filenames) in os.walk(default_folder) for f in filenames]
        try:
            task = current_user.launch_task("backup_files", list_of_files)
            db.session.commit()
        except Exception as exc:
            raise RuntimeError from exc
        flash(f"Backup started, task-id: {task.id}")

    return render_template(
        "backup.html",
        title="Upload",
        upload_form=upload_form,
        sync_backup_form=sync_backup_form
    )


@login_required  # type: ignore[misc]
@main.get("/restore")
def restore():
    """listing all files in a snapshot"""
    if not current_user.is_authenticated:
        return redirect(url_for("main.index"))

    restic_worker = ResticWorker(logger=current_app.logger)
    # todo: try me b
    response = restic_worker.files_in_snapshot()
    if len(response["errors"]):
        for error in response["errors"]:
            flash(error)

    return render_template("restore.html", title="Restore Files", files=response["files"])


@login_required  # type: ignore[misc]
@main.get("/restore/<snapshot_id>/<path>/<file_name>")
def restore_file(snapshot_id: str, path: str, file_name: str):
    """listing all files in a snapshot"""
    if not current_user.is_authenticated:
        return redirect(url_for("main.index"))

    restic_worker = ResticWorker(logger=current_app.logger)
    # todo: try me b
    was_restored = restic_worker.restore(snapshot_id, path, file_name)
    if was_restored:
        flash("The file has been restored!")
        # the reference to the parent dir is needed as the current working dir is /app
        restore_dir = "../" + current_app.config["RESTIC_RESTORE_DIR"]
        return send_from_directory(restore_dir, file_name, as_attachment=True)
    else:
        flash(
            f"Something went wrong! "
            f'The restoring process for the file "{file_name}" failed!'
        )

    return redirect(url_for("main.restore"))


@login_required  # type: ignore[misc]
@main.get("/delete/<snapshot_id>/<path>/<file_name>")
def delete_file(snapshot_id: str, path: str, file_name: str):
    """listing all files in a snapshot"""
    if not current_user.is_authenticated:
        return redirect(url_for("main.index"))

    restic_worker = ResticWorker(logger=current_app.logger)
    # todo: try me b
    was_deleted = restic_worker.remove_file(snapshot_id, path, file_name)
    if not was_deleted:
        flash(
            f"Something went wrong! "
            f'The deleting process for the file "{file_name}" failed!'
        )
    else:
        flash("The file has been deleted!")

    return redirect(url_for("main.restore"))


@login_required  # type: ignore[misc]
@main.route("/device", methods=["GET", "POST"])
def device() -> Response | str:
    if not current_user.is_authenticated:
        return redirect(url_for("main.index"))

    reboot_form = RebootDeviceForm()
    if reboot_form.validate_on_submit():
        device_info: DeviceInfo = current_app.extensions["device_info"]
        device_info.reboot(1)
        flash("Device will reboot shortly")

    shutdown_form = ShutdownDeviceForm()
    if shutdown_form.validate_on_submit():
        device_info: DeviceInfo = current_app.extensions["device_info"]
        device_info.shutdown(1)
        flash("Device will shutdown shortly")

    scheduler = current_app.extensions["scheduler"]
    list_of_job_instances = scheduler.get_jobs()
    return render_template(
        "device.html",
        title="Device",
        tasks=list_of_job_instances,
        reboot_form=reboot_form,
        shutdown_form=shutdown_form
    )


@login_required  # type: ignore[misc]
@main.route("/sync", methods=["GET", "POST"])
def sync() -> Response | str:
    # todo: this always submits both forms, pls fix
    if not current_user.is_authenticated:
        return redirect(url_for("main.index"))

    syncthing_worker: SyncthingWorker = current_app.extensions["syncthing"]

    add_device_form = AddSyncDeviceForm()
    if add_device_form.validate_on_submit():
        if not add_device_form.device_name.data:
            device_name = "unknown name"
        else:
            device_name = add_device_form.device_name.data
        result = syncthing_worker.add_device(add_device_form.device_id.data, device_name)
        if not result:
            current_app.logger.error("failed to add syncthing device")
            flash("failed to add syncthing device")
            return redirect(url_for("main.sync"))
        else:
            flash("Added SyncThing device")

    device_to_folder_form = AddSyncDeviceToFolderForm()
    if device_to_folder_form.validate_on_submit():
        result = syncthing_worker.share_folder_with_device(
            syncthing_worker.default_folder_id,
            device_to_folder_form.device_id.data
        )
        if not result:
            current_app.logger.error("failed to add device to folder")
            flash("failed to add device to folder")
            return redirect(url_for("main.sync"))
        else:
            flash("Added device to default folder")

    files = syncthing_worker.get_files_in_folder()
    return render_template(
        "sync.html",
        title="Sync",
        files=files,
        add_device_form=add_device_form,
        device_to_folder_form=device_to_folder_form
    )


@login_required  # type: ignore[misc]
@main.get("/account")
def account() -> Response | str:
    if not current_user.is_authenticated:
        return redirect(url_for("main.index"))

    return render_template("account.html", title="Account")


@login_required  # type: ignore[misc]
@main.get("/result/<task_id>")
def task_result(task_id: str) -> Response | str | dict[str, str | int | bool]:
    """get the current status of a rq task"""
    if not current_user.is_authenticated:
        return redirect(url_for("main.index"))

    task = db.session.get(Task, task_id)
    return {
        "name": task.name,
        "id": task.id,
        "complete": task.complete,
        "user_id": task.user_id,
    }


@main.get("/index")
@main.get("/")
@login_required  # type: ignore[misc]
def index() -> str:
    """render the main template"""
    return render_template("index.html", title="Home")


@auth.route("/register", methods=["GET", "POST"])
def register() -> str | Response:
    """
    render the register template or
    check the submitted form and create a new user
    """
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))

    form = RegistrationForm()
    # user submitted the form
    if form.validate_on_submit():
        user = db.session.scalar(select(User).where(User.email == "placeholder"))
        if not user.valid_password(form.password.data):
            flash("Invalid password")
            return redirect(url_for("auth.register"))

        user.email = form.email.data
        db.session.commit()
        # todo: tell the API and confirm the password was saved
        flash("Congratulations, you are now a registered user!")
        return redirect(url_for("auth.login"))

    # create new user
    word_file = xp.locate_wordfile("ger-anlx")  # german word list
    random_words = xp.generate_wordlist(
        wordfile=word_file,
        min_length=5,
        max_length=6,
        valid_chars="[a-z]"  # no umlaut
    )
    password = xp.generate_xkcdpassword(random_words, numwords=7, delimiter="-")
    user = db.session.scalar(select(User).where(User.email == "placeholder"))
    if user is None:
        user = User(email="placeholder")
    user.set_password(password)
    db.session.add(user)
    db.session.commit()

apps/gui/app/templates/account.html
{% extends "base.html" %}

{% block content %}
<a href="{{ url_for('auth.logout') }}">Logout</a>
<br>
<br>
<a href="{{ url_for('auth.create_totp') }}">Set up TOTP</a>
{% endblock %}

apps/gui/app/templates/backup.html
{% extends "base.html" %}

{% block content %}
    <h1>Upload</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {{ upload_form.hidden_tag() }}
        <p>
            {{ upload_form.backup_files.label }}<br>
            {{ upload_form.backup_files }}<br>
            {% for error in upload_form.backup_files.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ upload_form.submit() }}</p>
    </form>
    <hr>
    <h1>Syncthing Backup</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {{ sync_backup_form.hidden_tag() }}
        <p>{{ sync_backup_form.submit() }}</p>
    </form>
{% endblock %}

apps/gui/app/templates/base.html
<!doctype html>
<html lang="de">
    <head>
        <meta charset="UTF-8">
        {% if title %}
            <title>{{ title }} - Skarabäus</title>
        {% else %}
            <title>Skarabäus</title>
        {% endif %}
        <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
    </head>
    <body>
        {% include 'nav.html' %}
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
        {% include 'footer.html' %}
    </body>
</html>

apps/gui/app/templates/device.html
{% extends "base.html" %}

{% block content %}
    <h1>Device Actions</h1>
    <form action="" method="post">
        {{ reboot_form.hidden_tag() }}
        <p>{{ reboot_form.submit() }}</p>
    </form>
    <form action="" method="post">
        {{ shutdown_form.hidden_tag() }}
        <p>{{ shutdown_form.submit() }}</p>
    </form>
    <h1>Tasks</h1>
    <table>
        <tr>
            <th>id</th>
            <th>func_name</th>
            <th>created at</th>
            <th>started at</th>
            <th>finished</th>
            <th>result</th>
        </tr>
    {% for task in tasks %}
        <tr>
            <td>{{ task.id }}</td>
            <td>{{ task.func_name }}</td>
            <td>{{ task.created_at }}</td>
            <td>{{ task.started_at }}</td>
            <td>{{ task.is_finished }}</td>
            <td>{{ task.result }}</td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

apps/gui/app/templates/footer.html
<div class="wrapper">
    <div class="footer">
        <ul>
            <li><a href="">infos / documentation</a></li>
            <li><a href="">imprint</a></li>
            <li><a href="">support</a></li>
        </ul>
    </div>
</div>

apps/gui/app/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Hi, {{ current_user.email }}!</h1>
{% endblock %}

apps/gui/app/templates/login.html
{% extends "base.html" %}

{% block content %}
    <h1>Sign In</h1>
    <p>New User? <a href="{{ url_for('auth.register') }}">Click to Register!</a></p>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=32) }}
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.totp.label }}<br>
            {{ form.totp(size=32) }}
            {% for error in form.totp.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

apps/gui/app/templates/nav.html
<div class="wrapper">
    <nav class="header">
        <ul>
            <li><a href="{{ url_for('main.sync') }}">sync</a></li>
            <li><a href="{{ url_for('main.backup') }}">backup</a></li>
            <li><a href="{{ url_for('main.restore') }}">restore</a></li>
            <li><a href="{{ url_for('main.device') }}">device</a></li>
            <li><a href="{{ url_for('main.account') }}">account</a></li>
        </ul>
    </nav>
</div>

apps/gui/app/templates/register.html
{% extends "base.html" %}

{% block content %}
    <h1>Register</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=64) }}<br>
            {% for error in form.email.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        {% if password %}
            <p style="color: #ff7d00">{{ password }}</p>
            <p>This is your main password. Losing it, means losing your backup!</p>
            <p>Write it on two pieces of paper and put it in a safe! Give the second piece of paper your Cat/Dog.</p>
            <p style="color: red">No recovery possible!</p>
        {% endif %}
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=64) }}<br>
            {% for error in form.password.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.confirm_note }}{{ form.confirm_note.label }}<br>
            {% for error in form.confirm_note.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.confirm_no_recovery }}{{ form.confirm_no_recovery.label }}<br>
            {% for error in form.confirm_no_recovery.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

apps/gui/app/templates/restore.html
{% extends "base.html" %}

{% block content %}
    <h1>Files</h1>
    <table>
        <tr>
            <th>Select</th>
            <th>Restore</th>
            <th>File name</th>
            <th>Snapshot ID</th>
            <th>Permissions</th>
            <th>Backup Datetime</th>
            <th>Delete</th>
        </tr>
    {% for file in files %}
        <tr>
            <td><label>
                <input type="checkbox">
            </label></td>
            <td>
                <a href="{{ url_for('main.restore_file', snapshot_id=file.snapshot_id, path=file.base_path, file_name=file.file_name) }}">
                    Restore
                </a>
            </td>
            <td>{{ file.file_name }}</td>
            <td>{{ file.snapshot_id }}</td>
            <td>{{ file.permissions }}</td>
            <td>{{ file.backup_datetime }}</td>
            <td>
                <a href="{{ url_for('main.delete_file', snapshot_id=file.snapshot_id, path=file.base_path, file_name=file.file_name) }}">
                    Delete
                </a>
            </td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

apps/gui/app/templates/sync.html
{% extends "base.html" %}

{% block content %}
    <h1>Sync</h1>
    <form id="new_device" action="" method="post">
        {{ add_device_form.hidden_tag() }}
        <p>
            {{ add_device_form.device_id.label }}<br>
            {{ add_device_form.device_id(size=64) }}<br>
            {% for error in add_device_form.device_id.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ add_device_form.device_name.label }}<br>
            {{ add_device_form.device_name(size=64) }}<br>
            {% for error in add_device_form.device_name.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ add_device_form.submit() }}</p>
    </form>
    <form id="new_device_for_folder" action="" method="post">
        {{ device_to_folder_form.hidden_tag() }}
        <p>
            {{ device_to_folder_form.device_id.label }}<br>
            {{ device_to_folder_form.device_id(size=64) }}<br>
            {% for error in device_to_folder_form.device_id.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ device_to_folder_form.submit() }}</p>
    </form>
    <hr>
    <table>
        <tr>
            <th>file name</th>
            <th>size</th>
            <th>mod time</th>
        </tr>
    {% for file in files %}
        <tr>
            <td>{{ file.name }}</td>
            <td>{{ format_bytes(file.size) }}</td>
            <td>{{ file.modTime }}</td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

apps/gui/app/templates/totp.html
{% extends "base.html" %}

{% block content %}
    <h1>TOTP</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <img style="margin: 20px;" src="{{ qrcode(qr_code_text, error_correction='H', icon_img='icon.jpg', back_color='fff', fill_color='000')  }}" alt="qr-code-totp">
        <p>
            {{ form.setup_code.label }}<br>
            {{ form.setup_code(size=64) }}<br>
            {% for error in form.setup_code.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}